// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: friend_request.sql

package db

import (
	"context"
)

const createFriendRequest = `-- name: CreateFriendRequest :exec
INSERT INTO friend_requests (
    from_user_id, to_user_id, request_desc
) VALUES (
    $1, $2, $3
)
`

type CreateFriendRequestParams struct {
	FromUserID  int32  `json:"from_user_id"`
	ToUserID    int32  `json:"to_user_id"`
	RequestDesc string `json:"request_desc"`
}

func (q *Queries) CreateFriendRequest(ctx context.Context, arg *CreateFriendRequestParams) error {
	_, err := q.db.Exec(ctx, createFriendRequest, arg.FromUserID, arg.ToUserID, arg.RequestDesc)
	return err
}

const getFriendRequest = `-- name: GetFriendRequest :one
SELECT EXISTS (
	SELECT 1
	FROM friend_requests
	WHERE from_user_id = $1 AND to_user_id = $2 AND status = 1
)
`

type GetFriendRequestParams struct {
	FromUserID int32 `json:"from_user_id"`
	ToUserID   int32 `json:"to_user_id"`
}

// 检查申请是否存在
// SELECT * FROM friend_requests
// WHERE
//
//	from_user_id = $1 AND to_user_id = $2 AND status = 1;
func (q *Queries) GetFriendRequest(ctx context.Context, arg *GetFriendRequestParams) (bool, error) {
	row := q.db.QueryRow(ctx, getFriendRequest, arg.FromUserID, arg.ToUserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listFriendRequestByPending = `-- name: ListFriendRequestByPending :many
SELECT id, from_user_id, to_user_id, request_desc, status, created_at, updated_at FROM friend_requests 
WHERE 
	to_user_id = $1 AND status = 1
ORDER BY created_at DESC
`

func (q *Queries) ListFriendRequestByPending(ctx context.Context, toUserID int32) ([]FriendRequest, error) {
	rows, err := q.db.Query(ctx, listFriendRequestByPending, toUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FriendRequest{}
	for rows.Next() {
		var i FriendRequest
		if err := rows.Scan(
			&i.ID,
			&i.FromUserID,
			&i.ToUserID,
			&i.RequestDesc,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFriendRequest = `-- name: UpdateFriendRequest :exec
UPDATE friend_requests
SET
	status  = $3,
	updated_at = now()
WHERE
	(from_user_id = $1 AND to_user_id = $2 AND status = 1)
OR 
	(to_user_id = $1 AND from_user_id = $2 AND status = 1)
`

type UpdateFriendRequestParams struct {
	FromUserID int32 `json:"from_user_id"`
	ToUserID   int32 `json:"to_user_id"`
	Status     int8  `json:"status"`
}

func (q *Queries) UpdateFriendRequest(ctx context.Context, arg *UpdateFriendRequestParams) error {
	_, err := q.db.Exec(ctx, updateFriendRequest, arg.FromUserID, arg.ToUserID, arg.Status)
	return err
}
