// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: message.sql

package db

import (
	"context"
)

const createMessage = `-- name: CreateMessage :exec
INSERT INTO messages (
    session_id, sender_id, receiver_id, send_type, receiver_type, message_type, content
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
`

type CreateMessageParams struct {
	SessionID    string `json:"session_id"`
	SenderID     int32  `json:"sender_id"`
	ReceiverID   int32  `json:"receiver_id"`
	SendType     int8   `json:"send_type"`
	ReceiverType int8   `json:"receiver_type"`
	MessageType  int8   `json:"message_type"`
	Content      string `json:"content"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg *CreateMessageParams) error {
	_, err := q.db.Exec(ctx, createMessage,
		arg.SessionID,
		arg.SenderID,
		arg.ReceiverID,
		arg.SendType,
		arg.ReceiverType,
		arg.MessageType,
		arg.Content,
	)
	return err
}
