// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"time"
)

type FriendRequest struct {
	// 请求ID
	ID int32 `json:"id"`
	// 请求者ID
	SenderID int32 `json:"sender_id"`
	// 接收者ID
	ReceiverID int32 `json:"receiver_id"`
	// 请求信息
	RequestDesc string `json:"request_desc"`
	// 请求状态, 1: 待处理, 2: 已同意, 3: 已拒绝, 4: 已过期
	Status int8 `json:"status"`
	// 请求时间
	RequestedAt time.Time `json:"requested_at"`
	// 变更时间
	UpdatedAt time.Time `json:"updated_at"`
	// 申请过期时间
	ExpiredAt time.Time `json:"expired_at"`
}

type Friendship struct {
	// 用户ID
	UserID int32 `json:"user_id"`
	// 好友ID
	FriendID int32 `json:"friend_id"`
	// 好友备注
	Note string `json:"note"`
	// 创建时间
	CreatedAt time.Time `json:"created_at"`
}

type Group struct {
	// 群组ID
	ID int32 `json:"id"`
	// 群组名称
	GroupName string `json:"group_name"`
	// 创建者ID
	CreatorID int32 `json:"creator_id"`
	// 群组头像URL
	GroupAvatarUrl string `json:"group_avatar_url"`
	// 群组描述
	Description string `json:"description"`
	// 群组最大成员数, 默认500
	MaxMember int32 `json:"max_member"`
	// 群组创建时间
	CreatedAt time.Time `json:"created_at"`
	// 群组信息更新时间
	UpdatedAt time.Time `json:"updated_at"`
}

type GroupMember struct {
	// 群组ID
	GroupID int32 `json:"group_id"`
	// 用户ID
	UserID int32 `json:"user_id"`
	// 成员角色, 1: 群主, 2: 管理员, 3: 普通成员
	Role int8 `json:"role"`
	// 加入时间
	JoinedAt time.Time `json:"joined_at"`
}

type GroupRequest struct {
	// 请求ID
	ID int32 `json:"id"`
	// 请求者ID
	SenderID int32 `json:"sender_id"`
	// 接收者ID
	ReceiverID int32 `json:"receiver_id"`
	// 请求信息
	RequestDesc string `json:"request_desc"`
	// 请求状态, 1: 待处理, 2: 已同意, 3: 已拒绝, 4: 已忽略
	Status int8 `json:"status"`
	// 请求时间
	RequestedAt time.Time `json:"requested_at"`
	// 变更时间
	UpdatedAt time.Time `json:"updated_at"`
	// 申请过期时间
	ExpiredAt time.Time `json:"expired_at"`
}

type Message struct {
	// 消息ID
	ID int32 `json:"id"`
	// 会话ID, 用来做消息标识,格式:user/group:sender_id:receiver_id
	SessionID string `json:"session_id"`
	// 发送者ID
	SenderID int32 `json:"sender_id"`
	// 接收者ID, 用户或群组ID
	ReceiverID int32 `json:"receiver_id"`
	// 消息类型, 1: 私聊, 2: 群聊, 3: 心跳
	MessageType int8 `json:"message_type"`
	// 消息内容
	Content string `json:"content"`
	// 消息内容类型, 1: 文字, 2: 文件, 3: 图片, 4: 语音, 5: 视频
	ContentType int8 `json:"content_type"`
	// 读取状态, f: 未读, t: 已读
	ReadStatus bool `json:"read_status"`
	// 发送时间
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	// 用户ID
	ID int32 `json:"id"`
	// 用户名
	Username string `json:"username"`
	// 用户昵称
	Nickname string `json:"nickname"`
	// 用户密码
	Password string `json:"password"`
	// 用户邮箱
	Email string `json:"email"`
	// 用户性别, 1:男, 2:女, 3: 未知
	Gender int8 `json:"gender"`
	// 头像URL
	AvatarUrl string `json:"avatar_url"`
	// 上次密码更新时间
	PasswordChangedAt time.Time `json:"password_changed_at"`
	// 创建时间
	CreatedAt time.Time `json:"created_at"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at"`
}
