// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: user.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
	username, nickname, password, email, gender
) VALUES (
	$1, $2, $3, $4, $5
)
RETURNING id, username, nickname, password, email, gender, brithday, avatar_url, signature, password_changed_at, created_at, updated_at
`

type CreateUserParams struct {
	Username string `json:"username"`
	Nickname string `json:"nickname"`
	Password string `json:"password"`
	Email    string `json:"email"`
	Gender   int8   `json:"gender"`
}

func (q *Queries) CreateUser(ctx context.Context, arg *CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Nickname,
		arg.Password,
		arg.Email,
		arg.Gender,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Nickname,
		&i.Password,
		&i.Email,
		&i.Gender,
		&i.Brithday,
		&i.AvatarUrl,
		&i.Signature,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const existsEmail = `-- name: ExistsEmail :one
SELECT EXISTS (
	SELECT 1 FROM users
	WHERE email = $1
)
`

func (q *Queries) ExistsEmail(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, existsEmail, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const existsNickname = `-- name: ExistsNickname :one
SELECT EXISTS (
	SELECT 1 FROM users
	WHERE nickname = $1
)
`

func (q *Queries) ExistsNickname(ctx context.Context, nickname string) (bool, error) {
	row := q.db.QueryRow(ctx, existsNickname, nickname)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const existsUsername = `-- name: ExistsUsername :one
SELECT EXISTS (
	SELECT 1 FROM users 
	WHERE username = $1
)
`

func (q *Queries) ExistsUsername(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRow(ctx, existsUsername, username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getUser = `-- name: GetUser :one
SELECT id, username, nickname, password, email, gender, brithday, avatar_url, signature, password_changed_at, created_at, updated_at FROM users WHERE username = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUser, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Nickname,
		&i.Password,
		&i.Email,
		&i.Gender,
		&i.Brithday,
		&i.AvatarUrl,
		&i.Signature,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, nickname, password, email, gender, brithday, avatar_url, signature, password_changed_at, created_at, updated_at FROM users WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Nickname,
		&i.Password,
		&i.Email,
		&i.Gender,
		&i.Brithday,
		&i.AvatarUrl,
		&i.Signature,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, username, nickname, password, email, gender, brithday, avatar_url, signature, password_changed_at, created_at, updated_at FROM users WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserById(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Nickname,
		&i.Password,
		&i.Email,
		&i.Gender,
		&i.Brithday,
		&i.AvatarUrl,
		&i.Signature,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePwd = `-- name: UpdatePwd :exec
UPDATE users
SET
	password = $2,
	password_changed_at = now(),
	updated_at = now()
WHERE
	email = $1
`

type UpdatePwdParams struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

func (q *Queries) UpdatePwd(ctx context.Context, arg *UpdatePwdParams) error {
	_, err := q.db.Exec(ctx, updatePwd, arg.Email, arg.Password)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users 
SET
	gender = COALESCE($1, gender), 
	nickname = COALESCE($2, nickname), 
	updated_at = now()
WHERE id = $3
RETURNING id, username, nickname, password, email, gender, brithday, avatar_url, signature, password_changed_at, created_at, updated_at
`

type UpdateUserParams struct {
	Gender   pgtype.Int2 `json:"gender"`
	Nickname pgtype.Text `json:"nickname"`
	ID       int32       `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg *UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.Gender, arg.Nickname, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Nickname,
		&i.Password,
		&i.Email,
		&i.Gender,
		&i.Brithday,
		&i.AvatarUrl,
		&i.Signature,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
