[http]
host = "localhost"
port = 8080

[postgres]
host = "localhost"
port = 5432
username = "postgres"
password = "postgres"
db_name = "huanj"
ssl_mode = "disable"
driver = "postgres"
migrate_url = "file://db/migration"

[token]
token_symmetric_key = "plokmnjiuhbvgytfcxdreszawq564738"
access_token_duration = "30m"
refresh_token_duration = "24h"

[redis]
host = "localhost"
port = 6379

[secret]
enable = false