[http]
host = "192.168.172.136"
port = 8080

[postgres]
host = "localhost"
port = 5432
username = "postgres"
password = "postgres"
db_name = "dandelion"
ssl_mode = "disable"
driver = "postgres"
migrate_url = "file://db/migration"

[token]
token_symmetric_key = "plokmnjiuhbvgytfcxdreszawq564738"
access_token_duration = "30m"
refresh_token_duration = "24h"

[redis]
host = "localhost"
port = 6379